### ISSUE TITLE
401 api response

### ISSUE THREAD

**Issue by LegendaryGeek** [jwoglom/tconnectsync#10]
```
No event index change: 91532

Sleeping 60 seconds after unexpected no index change

New event index: 91631 last: 91532

Downloading t:connect ControlIQ data

Traceback (most recent call last):

File "/home/appuser/main.py", line 69, in <module>

main()

File "/home/appuser/main.py", line 62, in main

process_auto_update(tconnect, nightscout, time_start, time_end, args.pretend)

File "/home/appuser/tconnectsync/autoupdate.py", line 31, in process_auto_update

added = process_time_range(tconnect, nightscout, time_start, time_end, pretend)

File "/home/appuser/tconnectsync/process.py", line 35, in process_time_range

raise e

File "/home/appuser/tconnectsync/process.py", line 26, in process_time_range

ciqTherapyTimelineData = tconnect.controliq.therapy_timeline(time_start, time_end)

File "/home/appuser/tconnectsync/api/controliq.py", line 73, in therapy_timeline

return self.get('therapytimeline/users/%s' % (self.userGuid), {

File "/home/appuser/tconnectsync/api/controliq.py", line 63, in get

raise ApiException(r.status_code, "ControlIQ API HTTP %s response: %s" % (str(r.status_code), r.text))

tconnectsync.api.common.ApiException: ControlIQ API HTTP 401 response:
```
acording to google, 401 is accessing someting without proper credientals. so ya. there is that. i really wish i could help, but ive not got the time to learn the python rn, but its on my list of things to do!

**Comment by jwoglom** [comment]
Hopefully we can get this gone for good. try the latest build, I added explicit retry logic (in addition to using tandem's estimated expiration time) for whenever there's a http 401 in the api and forced a relogin.

**Comment by LegendaryGeek** [comment]
its pretty late for me here, so im going to get some sleep and let it run like i usually do. will get back once i see if it has stopped

**Comment by LegendaryGeek** [comment]
```
New event index: 95118 last: 95018

Downloading t:connect ControlIQ data

Downloading t:connect CSV data

HTTP 500 in therapy_timeline_csv (retry count 0): WS2 API HTTP 500 response: Options,Error,Output,ResponseStatus

,,,"{ErrorCode:XmlException,Message:Root element is missing.,Errors:[]}"

(HTTP 500)

HTTP 500 in therapy_timeline_csv (retry count 1): WS2 API HTTP 500 response: Options,Error,Output,ResponseStatus

,,,"{ErrorCode:XmlException,Message:Root element is missing.,Errors:[]}"

(HTTP 500)

HTTP 500 in therapy_timeline_csv (retry count 2): WS2 API HTTP 500 response: Options,Error,Output,ResponseStatus

,,,"{ErrorCode:XmlException,Message:Root element is missing.,Errors:[]}"

(HTTP 500)

Traceback (most recent call last):

File "/home/appuser/tconnectsync/api/ws2.py", line 67, in therapy_timeline_csv

req_text = self.get('therapytimeline2csv/%s/%s/%s?format=csv' % (self.userGuid, startDate, endDate), {})

File "/home/appuser/tconnectsync/api/ws2.py", line 23, in get

raise ApiException(r.status_code, "WS2 API HTTP %s response: %s" % (str(r.status_code), r.text))

tconnectsync.api.common.ApiException: WS2 API HTTP 500 response: Options,Error,Output,ResponseStatus

,,,"{ErrorCode:XmlException,Message:Root element is missing.,Errors:[]}"

(HTTP 500)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

File "/home/appuser/tconnectsync/api/ws2.py", line 67, in therapy_timeline_csv

req_text = self.get('therapytimeline2csv/%s/%s/%s?format=csv' % (self.userGuid, startDate, endDate), {})

File "/home/appuser/tconnectsync/api/ws2.py", line 23, in get

raise ApiException(r.status_code, "WS2 API HTTP %s response: %s" % (str(r.status_code), r.text))

tconnectsync.api.common.ApiException: WS2 API HTTP 500 response: Options,Error,Output,ResponseStatus

,,,"{ErrorCode:XmlException,Message:Root element is missing.,Errors:[]}"

(HTTP 500)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

File "/home/appuser/main.py", line 69, in <module>

main()

File "/home/appuser/main.py", line 62, in main

process_auto_update(tconnect, nightscout, time_start, time_end, args.pretend)

File "/home/appuser/tconnectsync/autoupdate.py", line 31, in process_auto_update

added = process_time_range(tconnect, nightscout, time_start, time_end, pretend)

File "/home/appuser/tconnectsync/process.py", line 38, in process_time_range

csvdata = tconnect.ws2.therapy_timeline_csv(time_start, time_end)

File "/home/appuser/tconnectsync/api/ws2.py", line 72, in therapy_timeline_csv

return self.therapy_timeline_csv(start, end, tries+1)

File "/home/appuser/tconnectsync/api/ws2.py", line 72, in therapy_timeline_csv

return self.therapy_timeline_csv(start, end, tries+1)

File "/home/appuser/tconnectsync/api/ws2.py", line 73, in therapy_timeline_csv

raise e

File "/home/appuser/tconnectsync/api/ws2.py", line 67, in therapy_timeline_csv

req_text = self.get('therapytimeline2csv/%s/%s/%s?format=csv' % (self.userGuid, startDate, endDate), {})

File "/home/appuser/tconnectsync/api/ws2.py", line 23, in get

raise ApiException(r.status_code, "WS2 API HTTP %s response: %s" % (str(r.status_code), r.text))

tconnectsync.api.common.ApiException: WS2 API HTTP 500 response: Options,Error,Output,ResponseStatus

,,,"{ErrorCode:XmlException,Message:Root element is missing.,Errors:[]}"

(HTTP 500)
```
long error... appeared overnight while i was asleep

**Comment by jwoglom** [comment]
Looks like the same http 500 as before that's a bug on Tandem's end. I added some retry logic there but I suspect there's not really much more we can do.

I think the real solution for now is just that, if you've properly configured tconnectsync, this error should be ignorable so long as it doesn't happen continuously. The next time tandem's servers return actual data everything will be scraped and put into nightscout.

**Comment by LegendaryGeek** [comment]
well, im getting the 500 about 4 times a day now, but as you said, much cant be done, so i just need to keep hitting the lauch button as a 500 kills the program. but anyways, i thank you for all you've done
