### ISSUE TITLE
Version 2.1.9 generates error

### ISSUE THREAD

**Issue by vonstein2002** [jwoglom/tconnectsync#111]
**Describe the problem**
Traceback (most recent call last):
  File "/usr/local/bin/tconnectsync", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/tconnectsync/__init__.py", line 123, in main
    added, last_event_id = TandemSourceProcessTimeRange(tconnect, nightscout, tconnectDevice, pretend=args.pretend, features=args.features).process(time_start, time_end)
TypeError: ProcessTimeRange.__init__() missing 1 required positional argument: 'secret'

**To Reproduce**
tconnectsync --features BASAL BOLUS IOB PUMP_EVENTS PUMP_EVENTS_BASAL_SUSPENSION PROFILES -v

**Expected behavior**

**Setup details**

Operating system: Ubuntu 22.04.1
tconnectsync version (from --version): 2.1.3
On what platform are you using the t:connect mobile app? (Android or iOS) IOS
What version are you using of the t:connect mobile app? 2.8.2

**Terminal output**
2024-12-13 13:48:10 DEBUG    Set logging level to DEBUG
2024-12-13 13:48:10 WARNING  THIS VERSION OF TCONNECTSYNC READS DATA FROM TANDEM SOURCE, AND MAY CONTAIN BUGS!
2024-12-13 13:48:10 INFO     You may notice different behavior compared to older versions which utilized t:connect data sources.
2024-12-13 13:48:10 INFO     To report a bug or to get help, see https://github.com/jwoglom/tconnectsync/issues
2024-12-13 13:48:10 INFO     Enabled features: BASAL, BOLUS, IOB, PUMP_EVENTS, PUMP_EVENTS_BASAL_SUSPENSION, PROFILES
2024-12-13 13:48:10 DEBUG    Instantiating new TandemSourceApi
2024-12-13 13:48:10 INFO     Logging in to TandemSourceApi...
2024-12-13 13:48:10 INFO     Loaded cached credentials from /home/me/.config/tconnectsync/.creds_cache: saved at 2024-12-13T17:45:05.724542+00:00 (1 hr 3 min 4 sec ago), access token expiry 2024-12-14T01:45:05+00:00 (in 6 hr 56 min 54 sec)
2024-12-13 13:48:10 INFO     Successfully used cached credentials
2024-12-13 13:48:10 DEBUG    Starting new HTTPS connection (1): source.tandemdiabetes.com:443
2024-12-13 13:48:11 DEBUG    https://source.tandemdiabetes.com:443 "GET /api/reports/reportsfacade/34148c12-d1e0-44c7-8adc-d6e1f2f3fc92/pumpeventmetadata HTTP/1.1" 200 None
2024-12-13 13:48:11 INFO     Found 3 pumps: dict_keys(['521xx', '90599xx', '929xx'])
2024-12-13 13:48:11 INFO     Using most recent pump (serial: 929xx, tconnectDeviceId: 495700, last seen: 2024-12-13T13:18:12)
Traceback (most recent call last):
  File "/usr/local/bin/tconnectsync", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/tconnectsync/__init__.py", line 123, in main
    added, last_event_id = TandemSourceProcessTimeRange(tconnect, nightscout, tconnectDevice, pretend=args.pretend, features=args.features).process(time_start, time_end)
TypeError: ProcessTimeRange.__init__() missing 1 required positional argument: 'secret'

**Check Login output**
2024-12-13 13:55:01 WARNING  THIS VERSION OF TCONNECTSYNC READS DATA FROM TANDEM SOURCE, AND MAY CONTAIN BUGS!
2024-12-13 13:55:01 INFO     You may notice different behavior compared to older versions which utilized t:connect data sources.
2024-12-13 13:55:01 INFO     To report a bug or to get help, see https://github.com/jwoglom/tconnectsync/issues
2024-12-13 13:55:01 INFO     Enabled features: BASAL, BOLUS, PUMP_EVENTS, PROFILES
2024-12-13 13:55:01 INFO     Logging in to TandemSourceApi...
2024-12-13 13:55:01 INFO     Loaded cached credentials from /home/me/.config/tconnectsync/.creds_cache: saved at 2024-12-13T17:45:05.724542+00:00 (1 hr 9 min 55 sec ago), access token expiry 2024-12-14T01:45:05+00:00 (in 6 hr 50 min 3 sec)
2024-12-13 13:55:01 INFO     Successfully used cached credentials
2024-12-13 13:55:02 INFO     Found 3 pumps: dict_keys(['521xx', '90599xx', '929xx'])
2024-12-13 13:55:02 INFO     Using most recent pump (serial: 929xx, tconnectDeviceId: 495700, last seen: 2024-12-13T13:18:12)
Traceback (most recent call last):
  File "/usr/local/bin/tconnectsync", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/tconnectsync/__init__.py", line 123, in main
    added, last_event_id = TandemSourceProcessTimeRange(tconnect, nightscout, tconnectDevice, pretend=args.pretend, features=args.features).process(time_start, time_end)
TypeError: ProcessTimeRange.__init__() missing 1 required positional argument: 'secret'

**Additional context**

**Comment by jwoglom** [comment]
Sorry about that -- fixed in v2.2.0!
