### ISSUE TITLE
"Unable to import parser secrets from secret.py"

### ISSUE THREAD

**Issue by RGwenHovey** [jwoglom/tconnectsync#14]
With;
- up to date Arch Linux x86_64
- Python 3.9.6
- git cloned into a temporary directory
- .env file filled with known good values as per instructions :

Running "pipenv run tconnectsync" from one directory above "main.py", results in "Error: the command tconnectsync could not be found within PATH or Pipfile's [scripts]."

Also, the error message "Unable to import parser secrets from secret.py" is returned, no matter what combination of arguments I put after "python3 main.py", even just "-h", during initial testing. secret.py exists in the second tconnectsync directory (one below main.py), and attributes are the same as all other .py files (-rw-r--r--).  

Probably unrelated, but I had to manually 'pip install arrow' to get to this point.

Let me know what other troubleshooting data you might need.
Thanks

**Comment by jwoglom** [comment]
Would you mind running secret.py -- with `pipenv run python3 tconnectsync/secret.py` -- to see if it properly prints out all of the environment variables without any errors?

Beyond that I'd just make sure the .env file is in the same folder as main.py. You should be able to run `pipenv run tconnectsync` so long as you're in the same folder as main.py, which has the Pipfile containing the "[scripts]" section in it.

**Comment by skmerten** [comment]
I struggled with this for a while actually until I realized the issue on my side anyway. 
While listed in the Pipfile, python-dotenv didn't seem to install for whatever reason and caused the Secret.py to throw the above mentioned error.
I just ran the below line in my CMD and all is well now!

`pip install python-dotenv`

**Comment by jwoglom** [comment]
Glad you got it working, maybe you were bypassing the Pipenv virtual environment itself somehow, assuming that pip installing dotenv globally fixed the problem?

I'll close this issue since it seems resolved

**Comment by RGwenHovey** [comment]
@skmerten , installing python-dotenv seems to have fixed the issue, data is flowing now.

@jwoglom maybe add this to instructions / dependency lists?

**Comment by jwoglom** [comment]
@RGwenHovey I have python-dotenv in the Pipfile -- when setting up the pipenv environment do you see any messages about installing that dependency?

**Comment by ElyeM** [comment]
I also had the same issues.

Had to pip install arrow and some other modules manually , and afterwards I got the "Unable to import parser secrets from secret.py" error. After running pip install python-dotenv that error got fixed, but now I am getting the following error.

Traceback (most recent call last):
  File "main.py", line 83, in <module>
    main()
  File "main.py", line 79, in main
    added = process_time_range(tconnect, nightscout, time_start, time_end, args.pretend)
  File "C:\elye\tconnectsync\tconnectsync\process.py", line 33, in process_time_range
    ciqTherapyTimelineData = tconnect.controliq.therapy_timeline(time_start, time_end)
  File "C:\elye\tconnectsync\tconnectsync\api\__init__.py", line 30, in controliq
    self._ciq = ControlIQApi(self.email, self.password)
  File "C:\elye\tconnectsync\tconnectsync\api\controliq.py", line 24, in __init__
    self.login(email, password)
  File "C:\elye\tconnectsync\tconnectsync\api\controliq.py", line 32, in login
    soup = BeautifulSoup(initial.content, features='lxml')
  File "C:\Python38\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?


Any advice? should I open a separate ticket?

**Comment by skmerten** [comment]
@ElyeM  I also had that same issue too. Installing the following dependency fixed that for me:

`pip install lxml`

@jwoglom in pipenv, I didn't receive any errors or warnings when installing the dependencys but it still seemed to miss a few.

**Comment by ElyeM** [comment]
Thanks, works now.

**Comment by jwoglom** [comment]
Interesting -- not sure why this is happening given that the dependencies are listed in the Pipfile. Given that the packages necessary to install manually seem to vary a bit, I'm not sure whether there's any good steps I could place in the instructions for now.  I will re-open the issue in case others run into the same problem and are looking for a solution.

**Comment by skmerten** [comment]
@jwoglom 

I appreciate your time on that! Exciting. I will definitely give that a try and let you know what I find. 

I'm actually running it out of a Raspberry pi 4 that auto runs when plugged in. I have conflicting issues between multiple pipenv's I have been slacking on resolving so a fresh start  via a pip installation sounds good to me.
