### ISSUE TITLE
Runtime Errors

### ISSUE THREAD

**Issue by ChaseCarHG** [jwoglom/tconnectsync#2]
First build took overnight on a Synology for installing dependencies from Pipfile.lock, but it persevered. Now building using cache, build performs very very well.

My .env file is set up adjacent to the dockerfile in /volume1/docker/tconnectsync/
I am Eastern Daylight Time too.

Now, I'm so close yet so far...

MyUserName@SERVERNAME:/volume1/docker/tconnectsync$ docker build -t tconnectsync .
Sending build context to Docker daemon  161.3kB
Step 1/19 : FROM python:3.9-slim as base
 ---> b2b5367cdfd4
Step 2/19 : ENV LANG C.UTF-8
 ---> Using cache
 ---> 19f4b9cd64b4
Step 3/19 : ENV LC_ALL C.UTF-8
 ---> Using cache
 ---> d9b7e61b5051
Step 4/19 : ENV PYTHONDONTWRITEBYTECODE 1
 ---> Using cache
 ---> a687a2cd0a25
Step 5/19 : ENV PYTHONFAULTHANDLER 1
 ---> Using cache
 ---> 544bc9df5dfb
Step 6/19 : FROM base AS python-deps
 ---> 544bc9df5dfb
Step 7/19 : RUN pip install pipenv
 ---> Using cache
 ---> 7eb38a3e0f6b
Step 8/19 : RUN apt-get update && apt-get install -y --no-install-recommends gcc
 ---> Using cache
 ---> cbf00d210bec
Step 9/19 : COPY Pipfile .
 ---> Using cache
 ---> 66e07482e49b
Step 10/19 : COPY Pipfile.lock .
 ---> Using cache
 ---> aed461982635
Step 11/19 : RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy
 ---> Using cache
 ---> 690e8e891410
Step 12/19 : FROM base AS runtime
 ---> 544bc9df5dfb
Step 13/19 : COPY --from=python-deps /.venv /.venv
 ---> Using cache
 ---> 76c45c4c0944
Step 14/19 : ENV PATH="/.venv/bin:$PATH"
 ---> Using cache
 ---> 42f6080509b8
Step 15/19 : RUN useradd --create-home appuser
 ---> Using cache
 ---> fb81eef236e7
Step 16/19 : WORKDIR /home/appuser
 ---> Using cache
 ---> b9b5a398108c
Step 17/19 : USER appuser
 ---> Using cache
 ---> 61da1ca386a5
Step 18/19 : COPY . .
 ---> Using cache
 ---> 6ae19514c3d0
Step 19/19 : ENTRYPOINT ["python3", "-u", "main.py"]
 ---> Using cache
 ---> 2cac16cc5442
Successfully built 2cac16cc5442
Successfully tagged tconnectsync:latest

MyUserName@SERVERNAME:/volume1/docker/tconnectsync$ docker run tconnectsync --auto-update
Traceback (most recent call last):
  File "/home/appuser/main.py", line 355, in <module>
    main()
  File "/home/appuser/main.py", line 314, in main
    last_event = tconnect.android.last_event_uploaded(PUMP_SERIAL_NUMBER)
  File "/home/appuser/api/__init__.py", line 40, in android
    self._android = AndroidApi(self.email, self.password)
  File "/home/appuser/api/android.py", line 31, in __init__
    self.login(email, password)
  File "/home/appuser/api/android.py", line 56, in login
    self.patientObjectId = j["user"]["patientObjectId"]
KeyError: 'patientObjectId'

**Comment by ChaseCarHG** [comment]
Hold on, I think I found the issue... Synology-specific filesystem thing...

**Comment by jwoglom** [comment]
Cool, based on this error message my guess is that maybe the Tandem login API request failed, but it didn't return a HTTP failure status code.

By the way, in the future you can use the prebuilt docker image -- you don't need to build the entire project on your NAS

**Comment by ChaseCarHG** [comment]
Nope, wasn't a Synology .env filepath issue. Even tried 
`docker run --env-file /volume1/docker/tconnectsync/.env tconnectsync --auto-update`

I did just see your added Docker Hub option, and am tempted to wipe what I built and try it.

**Comment by ChaseCarHG** [comment]
Could it be a $ symbol in my password? What symbols do you know it supports? 
(Tandem's website gives me heck -- I should have made the username all lowercase. Turns out their username field is case sensitive!)

**Comment by jwoglom** [comment]
Yes, that would definitely do it. Put the password in single quotes.

**Comment by jwoglom** [comment]
The issue is that the shell is likely picking up everything after the '$' as an environment variable. e.g.:

```bash
$ PASSWORD=abcdef$ghijk python3 -c 'import os; print(os.environ.get("PASSWORD"))'
abcdef

$ PASSWORD='abcdef$ghijk' python3 -c 'import os; print(os.environ.get("PASSWORD"))'
abcdef$ghijk
```

**Comment by ChaseCarHG** [comment]
1. Changed to pre-build Docker Hub image.
2. Changed Tandem password to longer (>12 chars, <30 chars) without symbols.
3. Updated .env file and its password.
4. Encapsulated string values in single quotes.

Error message changed some: 
`TravisBennett@NAS014:/volume1/docker/tconnectsync$ docker run --env-file /volume1/docker/tconnectsync/.env jwoglom/tconnectsync:latest --auto-update
Traceback (most recent call last):
  File "/home/appuser/main.py", line 355, in <module>
    main()
  File "/home/appuser/main.py", line 314, in main
    last_event = tconnect.android.last_event_uploaded(PUMP_SERIAL_NUMBER)
  File "/home/appuser/api/__init__.py", line 40, in android
    self._android = AndroidApi(self.email, self.password)
  File "/home/appuser/api/android.py", line 31, in __init__
    self.login(email, password)
  File "/home/appuser/api/android.py", line 48, in login
    raise ApiException(r.status_code, 'Received HTTP %s during login: %s' % (r.status_code, r.text))
api.common.ApiException: Received HTTP 400 during login: {"statusCode":400,"status":400,"code":400,"message":"Bad Request","name":"invalid_request"}
`

So, took away all the encapsulating singlequotes, and error message changed again (not sure why): 
`TravisBennett@NAS014:/volume1/docker/tconnectsync$ docker run --env-file /volume1/docker/tconnectsync/.env jwoglom/tconnectsync:latest --auto-update
Traceback (most recent call last):
  File "/home/appuser/main.py", line 355, in <module>
    main()
  File "/home/appuser/main.py", line 314, in main
    last_event = tconnect.android.last_event_uploaded(PUMP_SERIAL_NUMBER)
  File "/home/appuser/api/__init__.py", line 40, in android
    self._android = AndroidApi(self.email, self.password)
  File "/home/appuser/api/android.py", line 31, in __init__
    self.login(email, password)
  File "/home/appuser/api/android.py", line 56, in login
    self.patientObjectId = j["user"]["patientObjectId"]
KeyError: 'patientObjectId'
`

Would you be willing to review my .env file? If we can get this working, I'll legit send you a case of beer, or whatever you'd prefer.

**Comment by jwoglom** [comment]
I just pushed some new code to include some more debug output, would you mind pulling the most recent image from Docker Hub and sharing the output of what you're running again?

Should just need to run `docker pull jwoglom/tconnectsync:latest` and then re-run what you did above.

I have a theory, just want to see what their API is responding with.

**Comment by jwoglom** [comment]
Actually, just noticed that the log info I was looking for is still in your traceback! 

Anyways, my theory is that Tandem might be expecting some weird sanitization of special characters on this API endpoint. Try running tconnectsync without --auto-update and let me know if you get the same error from the controliq API, or if that API lets you through.

**Comment by ChaseCarHG** [comment]
Docker a pulled a new ef1a55b64252 from jwoglom/tconnectsync:latest.
`
Username@SERVERNAME:/volume1/docker/tconnectsync$ docker pull jwoglom/tconnectsync:latest
latest: Pulling from jwoglom/tconnectsync
6f28985ad184: Already exists
2cab076f918f: Already exists
a1a3f2ca0e75: Already exists
2a1aa0b42858: Already exists
a2ca14e613f1: Already exists
ef1a55b64245: Pull complete
f86ed388d72e: Pull complete
6eddbad637f6: Pull complete
Digest: sha256:c2ce785802e8d15c4ca5d10e8300230d1701dab464b1ef871dc26af715f2cc13
Status: Downloaded newer image for jwoglom/tconnectsync:latest
`
So then I ran it again... again _without_ any sort of string encapsulation in the .env file because I'm reading Docker doesn't like it.
`
Username@SERVERNAME:/volume1/docker/tconnectsync$ docker run --env-file /volume1/docker/tconnectsync/.env jwoglom/tconnectsync:latest --auto-update
`
Results: 
`Traceback (most recent call last):
  File "/home/appuser/main.py", line 355, in <module>
    main()
  File "/home/appuser/main.py", line 314, in main
    last_event = tconnect.android.last_event_uploaded(PUMP_SERIAL_NUMBER)
  File "/home/appuser/api/__init__.py", line 40, in android
    self._android = AndroidApi(self.email, self.password)
  File "/home/appuser/api/android.py", line 31, in __init__
    self.login(email, password)
  File "/home/appuser/api/android.py", line 47, in login
    raise ApiLoginException(r.status_code, 'Received HTTP %s during login: %s' % (r.status_code, r.text))
api.common.ApiLoginException: Received HTTP 400 during login: {"statusCode":400,"status":400,"code":400,"message":"Bad Request","name":"invalid_request"}
`

**Comment by jwoglom** [comment]
Try removing `--auto-update` just to see if it progresses any further, if you don't mind

**Comment by ChaseCarHG** [comment]
Did one of your environment variables get hardcoded somewhere?
I'm on the same TIMEZONE_NAME=America/New_York

`Username@SERVER:/volume1/docker/tconnectsync$ docker run --env-file /volume1/docker/tconnectsync/.env jwoglom/tconnectsync:latest
Processing data between 2021-03-16 01:12:46.683986 and 2021-03-17 01:12:46.683986
Downloading t:connect ControlIQ data
Traceback (most recent call last):
  File "/home/appuser/main.py", line 355, in <module>
    main()
  File "/home/appuser/main.py", line 351, in main
    added = process_time_range(tconnect, time_start, time_end, args.pretend)
  File "/home/appuser/main.py", line 245, in process_time_range
    raise e
  File "/home/appuser/main.py", line 236, in process_time_range
    ciqBasalData = tconnect.controliq.therapy_timeline(time_start, time_end)
  File "/home/appuser/api/__init__.py", line 24, in controliq
    self._ciq = ControlIQApi(self.email, self.password)
  File "/home/appuser/api/controliq.py", line 17, in __init__
    self.login(email, password)
  File "/home/appuser/api/controliq.py", line 37, in login
    raise ApiLoginException(req.status_code, 'Error logging in to t:connect. Check your login credentials.')
api.common.ApiLoginException: Error logging in to t:connect. Check your login credentials.
`

So to check it, I opened a Google Chrome private browser window to [t:connect](https://tconnect.tandemdiabetes.com/login.aspx?ReturnUrl=%2f)
and copied and pasted in my login info from the .env file. For some reason the same info that's been working fine in the Android app wouldn't work on this T:Connect site. So I set up my username and password through the link above, and now it is running smooth without the --auto-update flag.

I know this sounds like I typo'd something, but I can only promise that was not the case.
I see Android is still sending info. I think the key is the password **has** to be set using the desktop site and the link above.

With the --auto-update flag, there is still an error: 
`TravisBennett@NAS014:/volume1/docker/tconnectsync$ docker run --env-file /volume1/docker/tconnectsync/.env jwoglom/tconnectsync:latest --auto-update
Traceback (most recent call last):
  File "/home/appuser/main.py", line 355, in <module>
    main()
  File "/home/appuser/main.py", line 314, in main
    last_event = tconnect.android.last_event_uploaded(PUMP_SERIAL_NUMBER)
  File "/home/appuser/api/__init__.py", line 40, in android
    self._android = AndroidApi(self.email, self.password)
  File "/home/appuser/api/android.py", line 31, in __init__
    self.login(email, password)
  File "/home/appuser/api/android.py", line 58, in login
    self.patientObjectId = j["user"]["patientObjectId"]
KeyError: 'patientObjectId'
`

**Comment by ChaseCarHG** [comment]
Seems to be something specific to the --auto-update feature.

**Comment by ChaseCarHG** [comment]
I haven't done anything with Supervisord or Pipenv... just attempting to manually start the Docker container with 
`/volume1/docker/tconnectsync$ docker run --env-file /volume1/docker/tconnectsync/.env jwoglom/tconnectsync:latest --auto-update
`

**Comment by jwoglom** [comment]
Interesting!

For some background, the auto-update feature relies on the reverse-engineered Android API, which the non auto-update functionality doesn't use. Based on what you said, maybe you confused Tandem's back-end systems into thinking some parts of them that you had one password, and another part of them that you had another? (Or perhaps I'm making an incorrect assumption in how Tandem handles accounts, and something actually is separate but in my case had the same username and password.)

The only hardcoding is in https://github.com/jwoglom/tconnectsync/blob/master/secret.py, where it defaults to dummy values if the fields aren't provided.

Glad you've gotten it working without auto-update! For now, you can use the cron approach to just run `docker run --env-file /volume1/docker/tconnectsync/.env jwoglom/tconnectsync:latest` every, e.g., 15 minutes, and get the same end result as the flag.

**Comment by ChaseCarHG** [comment]
I can go cron. Please let me know if auto-update might have changed enough for it to run for me. 

What will it be in the case of beer or other? (Serious)

**Comment by jwoglom** [comment]
There is no need!

I am doing okay, please donate money or time to someone who needs help more than I do.

I will keep this github issue open in case anyone else runs into issues with authenticating to the android api.

**Comment by sfls1397** [comment]
I'm running into a similar issue. I am using Docker and Supervisord on a Mac. I can run **docker run tconnectsync** just fine and it will update the data to Nightscout. However, when I run **docker run tconnectsync --auto-update** then I get the following error.

Starting auto-update between 2021-06-27 22:56:48.075136 and 2021-06-28 22:56:48.075136 
Traceback (most recent call last):
  File "/home/appuser/main.py", line 77, in <module>
    main()
  File "/home/appuser/main.py", line 70, in main
    process_auto_update(tconnect, nightscout, time_start, time_end, args.pretend)
  File "/home/appuser/tconnectsync/autoupdate.py", line 30, in process_auto_update
    last_event = tconnect.android.last_event_uploaded(PUMP_SERIAL_NUMBER)
  File "/home/appuser/tconnectsync/api/__init__.py", line 54, in android
    self._android = AndroidApi(self.email, self.password)
  File "/home/appuser/tconnectsync/api/android.py", line 41, in __init__
    self.login(email, password)
  File "/home/appuser/tconnectsync/api/android.py", line 72, in login
    self.patientObjectId = j["user"]["patientObjectId"]

**Comment by sfls1397** [comment]
Looks like it is working now. I have no idea why.  All I did was the following, but I have done that many times before. How do I update from the master branch and not have to fiddle with my .env file?

Open Docker application
Delete everything in Docker
Delete the tconnectsync folder
git clone https://github.com/[username]/tconnectsync.git
cd /users/peter/tconnectsync/
docker build -t tconnectsync .
docker run tconnectsync --auto-update

**Comment by jwoglom** [comment]
@sfls1397 when this issue occurred, did it happen immediately or after some delay when using the auto update feature?

The tconnect servers might have returned an error or invalid response of some kind that tconnectsync didn't know how to process. From the text of the error you shared it looks like that happened during login.

As for updating from the master branch, you can make a pull request with the upstream (jwoglom/tconnectsync) as the source and your private repo as the destination from within GitHub. You can also do this via the git cli but it's a little more complicated.

**Comment by sfls1397** [comment]
The error occurred immediately. One thing I am doing differently and don't know if it makes a difference is that I am pasting all three of these commands into the terminal and pressing enter. I used to do them one at a time. I'm guessing that is what the run.sh is for, rather than using a command line.

cd /users/peter/tconnectsync/
docker build -t tconnectsync .
docker run tconnectsync --auto-update
