### ISSUE TITLE
Fatal Parse Error on Date Format

### ISSUE THREAD

**Issue by rehudson** [jwoglom/tconnectsync#24]
I regularly encounter the following error:
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/arrow/parser.py", line 727, in _parse_multiformat
    raise ParserError(
arrow.parser.ParserError: Could not match input '' to any of the following formats: YYYY-MM-DD, YYYY-M-DD, YYYY-M-D, YYYY/MM/DD, YYYY/M/DD, YYYY/M/D, YYYY.MM.DD, YYYY.M.DD, YYYY.M.D, YYYYMMDD, YYYY-DDDD, YYYYDDDD, YYYY-MM, YYYY/MM, YYYY.MM, YYYY, W.

It seems to occur only during an extended bolus.  Once the extended bolus is over the error goes away.  I'll put the full debug output here:
 tconnectsync --auto-update --verbose
2021-12-11 11:39:17 DEBUG    Set logging level to DEBUG
2021-12-11 11:39:17 INFO     Enabled features: BASAL, BOLUS, IOB
Starting auto-update between 2021-12-10 11:39:17.665888 and 2021-12-11 11:39:17.665888 
2021-12-11 11:39:17 DEBUG    Instantiating new AndroidApi
2021-12-11 11:39:17 DEBUG    Starting new HTTPS connection (1): tdcservices.tandemdiabetes.com:443
2021-12-11 11:39:18 DEBUG    https://tdcservices.tandemdiabetes.com:443 "POST /cloud/oauth2/token HTTP/1.1" 200 345
2021-12-11 11:39:18 INFO     Logged in to AndroidApi successfully (expiration: 2021-12-12T00:39:18.046Z, in 7 hours, 59 minutes)
2021-12-11 11:39:18 DEBUG    Starting new HTTPS connection (1): tdcservices.tandemdiabetes.com:443
2021-12-11 11:39:18 DEBUG    https://tdcservices.tandemdiabetes.com:443 "GET /cloud/upload/getlasteventuploaded?sn=880757 HTTP/1.1" 200 48
2021-12-11 11:39:18 INFO     New reported t:connect data. (event index: 49149 last: None)
2021-12-11 11:39:18 INFO     Downloading t:connect ControlIQ data
2021-12-11 11:39:18 DEBUG    Instantiating new ControlIQApi
2021-12-11 11:39:18 INFO     Logging in to ControlIQApi...
2021-12-11 11:39:18 DEBUG    Starting new HTTPS connection (1): tconnect.tandemdiabetes.com:443
2021-12-11 11:39:18 DEBUG    https://tconnect.tandemdiabetes.com:443 "GET /login.aspx?ReturnUrl=%2F HTTP/1.1" 200 33832
2021-12-11 11:39:19 DEBUG    https://tconnect.tandemdiabetes.com:443 "POST /login.aspx?ReturnUrl=%2F HTTP/1.1" 302 148
2021-12-11 11:39:19 DEBUG    https://tconnect.tandemdiabetes.com:443 "POST /CookieCheck.aspx?ReturnUrl=%2F HTTP/1.1" 302 118
2021-12-11 11:39:19 DEBUG    https://tconnect.tandemdiabetes.com:443 "GET / HTTP/1.1" 200 165794
2021-12-11 11:39:20 INFO     Logged in to ControlIQApi successfully (expiration: 2021-12-12T00:39:19.094Z, in 7 hours, 59 minutes)
2021-12-11 11:39:20 DEBUG    Starting new HTTPS connection (1): tdcservices.tandemdiabetes.com:443
2021-12-11 11:39:20 DEBUG    https://tdcservices.tandemdiabetes.com:443 "GET /tconnect/controliq/api/therapytimeline/users/081b3701-3f3f-4f11-9a9e-c7d4bd709905?startDate=12-10-2021&endDate=12-11-2021 HTTP/1.1" 200 2038
2021-12-11 11:39:20 INFO     Downloading t:connect CSV data
2021-12-11 11:39:20 DEBUG    Instantiating new WS2Api
2021-12-11 11:39:20 DEBUG    Starting new HTTPS connection (1): tconnectws2.tandemdiabetes.com:443
2021-12-11 11:39:24 DEBUG    https://tconnectws2.tandemdiabetes.com:443 "GET /therapytimeline2csv/081b3701-3f3f-4f11-9a9e-c7d4bd709905/12-10-2021/12-11-2021?format=csv HTTP/1.1" 200 51819
2021-12-11 11:39:24 DEBUG    {'DeviceType': 't:slim X2 Insulin Pump', 'SerialNumber': '880757', 'Description': 'EGV', 'EventDateTime': '2021-12-11T11:12:58', 'Readings (CGM / BGM)': '73'}
2021-12-11 11:39:24 INFO     Last CGM reading from t:connect: 2021-12-11T11:12:58-05:00 (26 minutes ago)
2021-12-11 11:39:24 DEBUG    Creating basal event for unprocessed suspension: {'time': '2021-12-10 04:52:03-05:00', 'delivery_type': 'manual suspension', 'duration_mins': 26.2, 'basal_rate': 0.0}
2021-12-11 11:39:24 DEBUG    Creating basal event for unprocessed suspension: {'time': '2021-12-10 10:33:35-05:00', 'delivery_type': 'manual suspension', 'duration_mins': 3.7, 'basal_rate': 0.0}
2021-12-11 11:39:24 DEBUG    Creating basal event for unprocessed suspension: {'time': '2021-12-10 11:52:10-05:00', 'delivery_type': 'manual suspension', 'duration_mins': 0.6, 'basal_rate': 0.0}
2021-12-11 11:39:24 DEBUG    No CSV basal data found
2021-12-11 11:39:24 DEBUG    ns_write_basal_events: querying for last uploaded entry
2021-12-11 11:39:24 DEBUG    Starting new HTTPS connection (1): *****.herokuapp.com:443
2021-12-11 11:39:25 DEBUG    https://*****.herokuapp.com:443 "GET /api/v1/treatments?count=1&find%5BenteredBy%5D=Pump%20%28tconnectsync%29&find%5BeventType%5D=Temp%20Basal&ts=1639240764.892172 HTTP/1.1" 200 284
2021-12-11 11:39:25 INFO     Last Nightscout basal upload: 2021-12-11T15:27:54+00:00
2021-12-11 11:39:25 DEBUG    ns_write_basal_events: added 0 events
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/tconnectsync", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tconnectsync/__init__.py", line 85, in main
    process_auto_update(tconnect, nightscout, time_start, time_end, args.pretend, features=args.features)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tconnectsync/autoupdate.py", line 39, in process_auto_update
    added = process_time_range(tconnect, nightscout, time_start, time_end, pretend, features=features)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tconnectsync/process.py", line 87, in process_time_range
    bolusEvents = process_bolus_events(bolusData)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tconnectsync/sync/bolus.py", line 21, in process_bolus_events
    parsed = TConnectEntry.parse_bolus_entry(b)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tconnectsync/parser/tconnect.py", line 116, in parse_bolus_entry
    "bolex_completion_time": TConnectEntry._datetime_parse(data["BolexCompletionDateTime"]).format() if complete and extended_bolus else None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tconnectsync/parser/tconnect.py", line 65, in _datetime_parse
    return arrow.get(date, tzinfo=TIMEZONE_NAME)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/arrow/api.py", line 91, in get
    return _factory.get(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/arrow/factory.py", line 254, in get
    dt = parser.DateTimeParser(locale).parse_iso(arg, normalize_whitespace)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/arrow/parser.py", line 298, in parse_iso
    return self._parse_multiformat(datetime_string, formats)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/arrow/parser.py", line 727, in _parse_multiformat
    raise ParserError(
arrow.parser.ParserError: Could not match input '' to any of the following formats: YYYY-MM-DD, YYYY-M-DD, YYYY-M-D, YYYY/MM/DD, YYYY/M/DD, YYYY/M/D, YYYY.MM.DD, YYYY.M.DD, YYYY.M.D, YYYYMMDD, YYYY-DDDD, YYYYDDDD, YYYY-MM, YYYY/MM, YYYY.MM, YYYY, W.

**Comment by rehudson** [comment]
In case it's needed.  Running on a Mac (OS X 10.14.6).  Uploader phone is iOS.

**Comment by jwoglom** [comment]
Thanks for the report! I've uploaded a commit to fix this specific bug. There is a significant amount of work around extended boluses that tconnectsync doesn't yet properly capture (see #19 as well), so I'm going to wait until extended bolus support is in a better state before creating a new release. So if you'd like to get the fix for this specific error I'd recommend cloning a copy of tconnectsync from the master branch (or, to install the binary globally like you get with pip install tconnectsync, run `pip install git+https://github.com/jwoglom/tconnectsync@master#egg=tconnectsync`). I'm hoping to iron out some of the related bugs around extended boluses in the near future.
