### ISSUE TITLE
Unknown basal suspension event type

### ISSUE THREAD

**Issue by kswick** [jwoglom/tconnectsync#26]
I tried the --features option to include PUMP_EVENTS from the command line before adding it to my run.sh and I got the following error:
<pre><code>kristen_swick@instance-5:~$ tconnectsync --auto-update --features {BASAL,BOLUS,IOB,PUMP_EVENTS}
2021-12-27 20:01:28 INFO     Enabled features: BASAL, BOLUS, IOB, PUMP_EVENTS
Starting auto-update between 2021-12-26 20:01:28.755914 and 2021-12-27 20:01:28.755914 
2021-12-27 20:01:29 INFO     Logged in to AndroidApi successfully (expiration: 2021-12-28T04:01:29.065Z, in 7 hours, 59 minutes)
2021-12-27 20:01:29 INFO     New reported t:connect data. (event index: 36241 last: None)
2021-12-27 20:01:29 INFO     Downloading t:connect ControlIQ data
2021-12-27 20:01:29 INFO     Logging in to ControlIQApi...
2021-12-27 20:01:31 INFO     Logged in to ControlIQApi successfully (expiration: 2021-12-28T04:01:29.952Z, in 7 hours, 59 minutes)
2021-12-27 20:01:31 INFO     Downloading t:connect CSV data
2021-12-27 20:01:33 INFO     Last CGM reading from t:connect: 2021-12-27T14:41:13-05:00 (20 minutes ago)
2021-12-27 20:01:33 INFO     Last Nightscout basal upload: 2021-12-27T19:19:17+00:00
Traceback (most recent call last):
  File "/home/kristen_swick/.local/bin/tconnectsync", line 8, in <module>
    sys.exit(main())
  File "/home/kristen_swick/.local/lib/python3.8/site-packages/tconnectsync/__init__.py", line 85, in main
    process_auto_update(tconnect, nightscout, time_start, time_end, args.pretend, features=args.features)
  File "/home/kristen_swick/.local/lib/python3.8/site-packages/tconnectsync/autoupdate.py", line 39, in process_auto_update
    added = process_time_range(tconnect, nightscout, time_start, time_end, pretend, features=features)
  File "/home/kristen_swick/.local/lib/python3.8/site-packages/tconnectsync/process.py", line 97, in process_time_range
    bsPumpEvents = process_basalsuspension_events(ws2BasalSuspension)
  File "/home/kristen_swick/.local/lib/python3.8/site-packages/tconnectsync/sync/pump_events.py", line 41, in process_basalsuspension_events
    parsed = TConnectEntry.parse_basalsuspension_event(event)
  File "/home/kristen_swick/.local/lib/python3.8/site-packages/tconnectsync/parser/tconnect.py", line 179, in parse_basalsuspension_event
    raise UnknownBasalSuspensionEventException(data)
tconnectsync.parser.tconnect.UnknownBasalSuspensionEventException: Unknown basal suspension event type: {'EventDateTime': '/Date(1640541521000-0000)/', 'SuspendReason': 'temp-profile'}</code></pre>

Note: I already hadtconnectsync running continuously using supervisor using the default features so all of the other data should have already been up to date in Nightscout.

**Comment by jwoglom** [comment]
Thanks for the report! Can you go into Settings > History > Pump History > Complete, and find whatever events occurred at approximately 2021-12-26 09:58:41-05:00 (EST)? I suspect this is a Temporary Profile change event or something similar.

If you can confirm for me what this shows up as in pump history, then I'll make the associated change in tconnectsync to fix this.

**Comment by kswick** [comment]
Very cool! I hadn't poked around the history section of the menus yet. I've only been using this pump (or any pump) for a week and a half so I'm still on a steep learning curve.

There are 2 events for 9:58am and I don't see a way to view the seconds portion of the time stamp to tell which on was 09:58:41:
- Basal Rate Change
- Control-IQ Decrease

However, my first guess would be the Control-IQ Decrease one because I see a ton of other Basal Rate Change entries. I also see a Control-IQ Increase, Control-IQ Normal, and Control-IQ Suspend entries on that day.

![20211227_151830](https://user-images.githubusercontent.com/39632017/147504794-fc83df8b-3fb8-44df-89d3-6b2a1387cf6f.jpg)

Thanks! Let me know if there's anything else I can do to help!

**Comment by jwoglom** [comment]
Thanks for taking a look -- can you look at 9:58 AM rather than PM? (That is assuming your pump is in EST time)

**Comment by kswick** [comment]
*facepalm* I claim insanity due to exhaustion. I've been sick for a week at this point. Yes, in an ironic coincidence, I got sick just days after switching to the pump. This the first time I've been really sick since my T1D diagnosis 3.5 years ago.

The 9:58 *AM* entry is a Basal Rate Change to 0.000.
![20211227_154005](https://user-images.githubusercontent.com/39632017/147506054-6573df59-0102-4f1a-a7c3-813313c369ca.jpg)

P.S. Your response to my flub was insanely polite!

**Comment by jwoglom** [comment]
I have updated tconnectsync and released v0.6.3 which should fix this issue!
