### ISSUE TITLE
Can't get tconnectsync to work.

### ISSUE THREAD

**Issue by smatthew** [jwoglom/tconnectsync#3]
Any suggestions? I'm getting the following when running tconnectsync

`smatthew@Scotts-iMac tconnectsync % pipenv run tconnectsync
Loading .env environment variables...
Processing data between 2021-03-21 16:07:20.254153 and 2021-03-22 16:07:20.254153 
Downloading t:connect ControlIQ data
Downloading t:connect CSV data
Traceback (most recent call last):
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x1042764c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cgm-roberts.herokuapp.comapi', port=443): Max retries exceeded with url: /v1/treatments?count=1&find%5BenteredBy%5D=Pump%20%28tconnectsync%29&find%5BeventType%5D=Temp%20Basal&ts=1616454448.179522 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1042764c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/smatthew/Documents/src/tconnectsync/tconnectsync/main.py", line 59, in <module>
    main()
  File "/Users/smatthew/Documents/src/tconnectsync/tconnectsync/main.py", line 55, in main
    added = process_time_range(tconnect, time_start, time_end, args.pretend)
  File "/Users/smatthew/Documents/src/tconnectsync/tconnectsync/tconnectsync/process.py", line 54, in process_time_range
    added += ns_write_basal_events(basalEvents, pretend=pretend)
  File "/Users/smatthew/Documents/src/tconnectsync/tconnectsync/tconnectsync/sync/basal.py", line 68, in ns_write_basal_events
    last_upload = last_uploaded_nightscout_entry(BASAL_EVENTTYPE)
  File "/Users/smatthew/Documents/src/tconnectsync/tconnectsync/tconnectsync/nightscout.py", line 41, in last_uploaded_nightscout_entry
    latest = requests.get(NS_URL + 'api/v1/treatments?count=1&find[enteredBy]=' + urllib.parse.quote(ENTERED_BY) + '&find[eventType]=' + urllib.parse.quote(eventType) + '&ts=' + str(time.time()), headers={
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/smatthew/.local/share/virtualenvs/tconnectsync-MOJrdNEQ/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cgm-roberts.herokuapp.comapi', port=443): Max retries exceeded with url: /v1/treatments?count=1&find%5BenteredBy%5D=Pump%20%28tconnectsync%29&find%5BeventType%5D=Temp%20Basal&ts=1616454448.179522 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1042764c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
smatthew@Scotts-iMac tconnectsync % 
`

**Comment by jwoglom** [comment]
Hi, I think you might have specified your Nightscout address improperly. 

```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cgm-roberts.herokuapp.comapi', port=443):
```

Make sure your NS_URL ends in a slash and is a full url with http/https prefix

**Comment by smatthew** [comment]
Doh! I thought it was something like that......
Now it runs... but doesn't do anything. Any suggestions? 

```
smatthew@Scotts-iMac tconnectsync % pipenv run tconnectsync
Loading .env environment variables...
Processing data between 2021-03-21 18:26:51.460202 and 2021-03-22 18:26:51.460202 
Downloading t:connect ControlIQ data
Downloading t:connect CSV data
Last Nightscout basal upload: None
Last Nightscout bolus upload: None
Last Nightscout iob upload: None
No IOB events: skipping
Added 0 items
```

**Comment by jwoglom** [comment]
Hm, do you mind logging in to the t:connect website and verifying that data appears in the therapy timeline there?

I just added a `--check-login` option, which might also help. It will try to log in to each API and output some data from it, and might help see whether there is any data in t:connect that this script can query.

You can also try increasing the date range using the --days option, in case there is no uploaded pump data from the past day.
