### ISSUE TITLE
ws2 api 500 error 

### ISSUE THREAD

**Issue by LegendaryGeek** [jwoglom/tconnectsync#9]
```
New event index: 83187 last: 83092

Downloading t:connect ControlIQ data

Downloading t:connect CSV data

Traceback (most recent call last):

File "/home/appuser/main.py", line 64, in <module>

main()

File "/home/appuser/main.py", line 57, in main

process_auto_update(tconnect, time_start, time_end, args.pretend)

File "/home/appuser/tconnectsync/autoupdate.py", line 31, in process_auto_update

added = process_time_range(tconnect, time_start, time_end, pretend)

File "/home/appuser/tconnectsync/process.py", line 38, in process_time_range

csvdata = tconnect.ws2.therapy_timeline_csv(time_start, time_end)

File "/home/appuser/tconnectsync/api/ws2.py", line 61, in therapy_timeline_csv

req_text = self.get('therapytimeline2csv/%s/%s/%s?format=csv' % (self.userGuid, startDate, endDate), {})

File "/home/appuser/tconnectsync/api/ws2.py", line 18, in get

raise ApiException(r.status_code, "WS2 API HTTP %s response: %s" % (str(r.status_code), r.text))

tconnectsync.api.common.ApiException: WS2 API HTTP 500 response: Options,Error,Output,ResponseStatus

,,,"{ErrorCode:XmlException,Message:Root element is missing.,Errors:[]}"
```
i run into all the errors... anywayhere is the latest one

**Comment by jwoglom** [comment]
I've run into this before -- it's a bug on Tandem's side which seems to happen to me if you querying too much data at once. Unfortunately not much more to do besides just be patient and try it again and hope it doesn't error -- or possibly use the start/end options to go one day at a time if you're loading in a lot of bulk data.

**Comment by LegendaryGeek** [comment]
ah, okay

**Comment by LegendaryGeek** [comment]
not going to reopen, because as you said, you cant do anything about it, but ive just been running autoupdate, and as i have ive been getting at least 2 of these a day

**Comment by jwoglom** [comment]
I added some rudimentary retry logic, please take a look and try out the new build

**Comment by LegendaryGeek** [comment]
```
PS F:\tconnectsync\tconnectsync> docker run tconnectsync --auto-update
Starting auto-update between 2021-04-24 11:47:18.780581 and 2021-04-25 11:47:18.780581
Traceback (most recent call last):
  File "/home/appuser/main.py", line 69, in <module>
    main()
  File "/home/appuser/main.py", line 62, in main
    process_auto_update(tconnect, nightscout, time_start, time_end, args.pretend)
  File "/home/appuser/tconnectsync/autoupdate.py", line 23, in process_auto_update
    last_event = tconnect.android.last_event_uploaded(PUMP_SERIAL_NUMBER)
  File "/home/appuser/tconnectsync/api/__init__.py", line 44, in android
    self._android = AndroidApi(self.email, self.password)
  File "/home/appuser/tconnectsync/api/android.py", line 36, in __init__
    self.login(email, password)
  File "/home/appuser/tconnectsync/api/android.py", line 52, in login
    raise ApiLoginException(r.status_code, 'Received HTTP %s during login: %s' % (r.status_code, r.text))
tconnectsync.api.common.ApiLoginException: Received HTTP 400 during login: {"statusCode":400,"status":400,"code":400,"message":"Max attempted logins exceeded.","name":"invalid_request"}
```
so. this happened when i tried it.

**Comment by LegendaryGeek** [comment]
oh. nvm. forgot to add my credientials to the latest container...
