### ISSUE TITLE
No longer able to pull data from tandem website through API

### ISSUE THREAD

**Issue by bcleonard** [jwoglom/tconnectsync#90]
**Describe the problem**

Starting 04/22/2024, I'm not longer able to pull data from tandem's website.  Its pretty strange.   Its been working for months.   I had assumed that it was login related, but i've validated my login information.

**To Reproduce**
1. ...
2. ...

**Expected behavior**
I expect that pump information to be pulled from tandem to be pushed to nightscout.

**Setup details**

* docker on Rocky 8.9
* **tconnectsync version** (from `--version`): 0.9.6
* **On what platform are you using the t:connect mobile app?** iOS
* **What version are you using of the t:connect mobile app?**  2.7.1

**Terminal output**

Processing data between 2024-04-23 23:00:47.273036 and 2024-04-24 23:00:47.273036
2024-04-24 23:00:47 INFO     Enabled features: BASAL, BOLUS, PUMP_EVENTS
2024-04-24 23:00:47 INFO     Downloading t:connect ControlIQ data
2024-04-24 23:00:47 INFO     Logging in to ControlIQApi...
2024-04-24 23:00:47 INFO     Reported tconnect software version: t:connect 7.17.1.2
2024-04-24 23:00:47 WARNING  Newer API version than last confirmed working. Saw t:connect 7.17.1.2 and expected t:connect 7.16.0.1
2024-04-24 23:00:47 WARNING  If you experience any issues, please report them to https://github.com/jwoglom/tconnectsync
2024-04-24 23:00:48 INFO     Logged in to ControlIQApi successfully (expiration: 2024-04-25T07:18:21.750Z, in 8 hours, 17 minutes)
2024-04-24 23:00:48 INFO     Downloading t:connect therapy_events
2024-04-24 23:00:48 WARNING  No last CGM reading is able to be determined from CIQ
2024-04-24 23:00:48 WARNING  Downloading t:connect CSV data
2024-04-24 23:00:48 WARNING  Falling back on WS2 CSV data source because BOLUS is an enabled feature and CIQ bolus data was empty!!
2024-04-24 23:00:48 WARNING  <!!> The WS2 data source is unreliable and may prevent timely synchronization
2024-04-24 23:00:49 WARNING  No last CGM reading is able to be determined from CSV
2024-04-24 23:00:50 WARNING  last_uploaded_entry with t_to_space: Nightscout last_uploaded_entry 500 response: <html>
  <head>
    <meta charset='utf-8'>
    <title>Error: Cannot parse 2024-04-23+23:00:47.273036 00:00 as a valid ISO-8601 date</title>
    <style>* {
  margin: 0;
  padding: 0;
  outline: 0;
}

body {
  padding: 80px 100px;
  font: 13px "Helvetica Neue", "Lucida Grande", "Arial";
  background: #ECE9E9 -webkit-gradient(linear, 0% 0%, 0% 100%, from(#fff), to(#ECE9E9));
  background: #ECE9E9 -moz-linear-gradient(top, #fff, #ECE9E9);
  background-repeat: no-repeat;
  color: #555;
  -webkit-font-smoothing: antialiased;
}
h1, h2 {
  font-size: 22px;
  color: #343434;
}
h1 em, h2 em {
  padding: 0 5px;
  font-weight: normal;
}
h1 {
  font-size: 60px;
}
h2 {
  margin-top: 10px;
}
ul li {
  list-style: none;
}
#stacktrace {
  margin-left: 60px;
}
</style>
  </head>
  <body>
    <div id="wrapper">
      <h1>Connect</h1>
      <h2><em>500</em> Error: Cannot parse 2024-04-23+23:00:47.273036 00:00 as a valid ISO-8601 date</h2>
      <ul id="stacktrace"><li> &nbsp; &nbsp;at /opt/multi/working/workdir/lib/server/query.js:71:17</li><li> &nbsp; &nbsp;at Array.forEach (&lt;anonymous&gt;)</li><li> &nbsp; &nbsp;at enforceDateFilter (/opt/multi/working/workdir/lib/server/query.js:62:28)</li><li> &nbsp; &nbsp;at create (/opt/multi/working/workdir/lib/server/query.js:120:5)</li><li> &nbsp; &nbsp;at query_for (/opt/multi/working/workdir/lib/server/treatments.js:121:12)</li><li> &nbsp; &nbsp;at Function.list (/opt/multi/working/workdir/lib/server/treatments.js:115:13)</li><li> &nbsp; &nbsp;at /opt/multi/working/workdir/lib/api/treatments/index.js:96:22</li><li> &nbsp; &nbsp;at Layer.handle [as handle_request] (/opt/multi/working/workdir/node_modules/express/lib/router/layer.js:95:5)</li><li> &nbsp; &nbsp;at next (/opt/multi/working/workdir/node_modules/express/lib/router/route.js:137:13)</li><li> &nbsp; &nbsp;at Route.dispatch (/opt/multi/working/workdir/node_modules/express/lib/router/route.js:112:3)</li></ul>
    </div>
  </body>
</html>
 (HTTP 500)
2024-04-24 23:00:50 INFO     Last Nightscout basal upload: None
2024-04-24 23:00:50 INFO     finalized bolusEvents: []
2024-04-24 23:00:51 WARNING  last_uploaded_entry with t_to_space: Nightscout last_uploaded_entry 500 response: <html>
  <head>
    <meta charset='utf-8'>
    <title>Error: Cannot parse 2024-04-23+23:00:47.273036 00:00 as a valid ISO-8601 date</title>
    <style>* {
  margin: 0;
  padding: 0;
  outline: 0;
}

body {
  padding: 80px 100px;
  font: 13px "Helvetica Neue", "Lucida Grande", "Arial";
  background: #ECE9E9 -webkit-gradient(linear, 0% 0%, 0% 100%, from(#fff), to(#ECE9E9));
  background: #ECE9E9 -moz-linear-gradient(top, #fff, #ECE9E9);
  background-repeat: no-repeat;
  color: #555;
  -webkit-font-smoothing: antialiased;
}
h1, h2 {
  font-size: 22px;
  color: #343434;
}
h1 em, h2 em {
  padding: 0 5px;
  font-weight: normal;
}
h1 {
  font-size: 60px;
}
h2 {
  margin-top: 10px;
}
ul li {
  list-style: none;
}
#stacktrace {
  margin-left: 60px;
}
</style>
  </head>
  <body>
    <div id="wrapper">
      <h1>Connect</h1>
      <h2><em>500</em> Error: Cannot parse 2024-04-23+23:00:47.273036 00:00 as a valid ISO-8601 date</h2>
      <ul id="stacktrace"><li> &nbsp; &nbsp;at /opt/multi/working/workdir/lib/server/query.js:71:17</li><li> &nbsp; &nbsp;at Array.forEach (&lt;anonymous&gt;)</li><li> &nbsp; &nbsp;at enforceDateFilter (/opt/multi/working/workdir/lib/server/query.js:62:28)</li><li> &nbsp; &nbsp;at create (/opt/multi/working/workdir/lib/server/query.js:120:5)</li><li> &nbsp; &nbsp;at query_for (/opt/multi/working/workdir/lib/server/treatments.js:121:12)</li><li> &nbsp; &nbsp;at Function.list (/opt/multi/working/workdir/lib/server/treatments.js:115:13)</li><li> &nbsp; &nbsp;at /opt/multi/working/workdir/lib/api/treatments/index.js:96:22</li><li> &nbsp; &nbsp;at Layer.handle [as handle_request] (/opt/multi/working/workdir/node_modules/express/lib/router/layer.js:95:5)</li><li> &nbsp; &nbsp;at next (/opt/multi/working/workdir/node_modules/express/lib/router/route.js:137:13)</li><li> &nbsp; &nbsp;at Route.dispatch (/opt/multi/working/workdir/node_modules/express/lib/router/route.js:112:3)</li></ul>
    </div>
  </body>
</html>
 (HTTP 500)
2024-04-24 23:00:51 INFO     Last Nightscout bolus upload: None
2024-04-24 23:00:51 INFO     Wrote 0 events to Nightscout this process cycle
Added 0 items

ignore the date issues, i've been getting them forever and they don't seem to mean anything.

**Check Login output**
tconnectsync version 0.9.6
Python version 3.9.18 (main, Oct 11 2023, 23:49:58)
[GCC 12.2.0]
System platform linux
Running checks with time range 2024-04-23 23:03:15.195403 to 2024-04-24 23:03:15.195403
Current time: 2024-04-24 23:03:15.195535
time.tzname: ('UTC', 'UTC')
Loading secrets...
TIMEZONE_NAME: America/Los_Angeles
-----
Logging in to t:connect ControlIQ API...
2024-04-24 23:03:15 INFO     Logging in to ControlIQApi...
2024-04-24 23:03:15 INFO     Reported tconnect software version: t:connect 7.17.1.2
2024-04-24 23:03:15 WARNING  Newer API version than last confirmed working. Saw t:connect 7.17.1.2 and expected t:connect 7.16.0.1
2024-04-24 23:03:15 WARNING  If you experience any issues, please report them to https://github.com/jwoglom/tconnectsync
2024-04-24 23:03:16 INFO     Logged in to ControlIQApi successfully (expiration: 2024-04-25T07:20:49.627Z, in 8 hours, 17 minutes)
2024-04-24 23:03:16 WARNING  Received ApiException in ControlIQApi with endpoint 'tconnect/controliq/api/summary/users/02ec58ff-0fa2-4c97-8802-df3b7361882a?startDate=04-23-2024&endDate=04-24-2024' (tries 0): ControlIQ API HTTP 404 response: {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"00-5ab172066da38d43b6f6b90e9269e4b4-c585b81aa3cf9c40-00"} (HTTP 404)
Error occurred querying ControlIQ API for dashboard_summary:
Traceback (most recent call last):
  File "/home/appuser/tconnectsync/check.py", line 85, in check_login
    summary = tconnect.controliq.dashboard_summary(time_start, time_end)
  File "/home/appuser/tconnectsync/api/controliq.py", line 164, in dashboard_summary
    return self.get('tconnect/controliq/api/summary/users/%s?startDate=%s&endDate=%s' % (self.userGuid, startDate, endDate), {})
  File "/home/appuser/tconnectsync/api/controliq.py", line 139, in get
    raise e
  File "/home/appuser/tconnectsync/api/controliq.py", line 122, in get
    return self._get(endpoint, query)
  File "/home/appuser/tconnectsync/api/controliq.py", line 116, in _get
    raise ApiException(r.status_code, "ControlIQ API HTTP %s response: %s" % (str(r.status_code), r.text))
tconnectsync.api.common.ApiException: ControlIQ API HTTP 404 response: {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"00-5ab172066da38d43b6f6b90e9269e4b4-c585b81aa3cf9c40-00"} (HTTP 404)

<!> The API returns a 404 error if there is no data for the provided dates (currently 2024-04-23 23:03:15.195403 - 2024-04-24 23:03:15.195403). Try re-running with an earlier start date using --start-date and --end-date arguments.
Querying ControlIQ therapy_timeline...
Querying ControlIQ therapy_events...
-----
Initializing t:connect WS2 API...
Querying WS2 therapy_timeline_csv...
-----
Logging in to t:connect Android API...
2024-04-24 23:03:18 INFO     Logged in to AndroidApi successfully (expiration: 2024-04-25T07:20:52.318Z, in 8 hours, 17 minutes)
-----
Logging in to Nightscout...
-----
Last basal start time: None (n/a)
Last basal duration: None
Last reading time: None (n/a)
-----

**Additional context**
There are two things that I can see that might be an issues.

1)  the line "Newer API version than last confirmed working. Saw t:connect 7.17.1.2 and expected t:connect 7.16.0.1"  I don't know if this is an issue or not
2)  the line "Processing data between 2024-04-23 23:00:47.273036 and 2024-04-24 23:00:47.273036"  this is basically no time so it won't pull any data.   Additionally, this is about 3.5 hours in the future so of course there won't be any data.

**Comment by MatthewMazaika** [comment]
i've noticed this happens periodically and it has always been Tandem issue, not an issue with this sync

check in your Tandem portal and see if you are missing data there as well - if the data isn't there, then it won't appear via this sync - ours went missing as of ~5pmCDT yesterday

things that sometimes fix it
* turn bluetooth off/on
* restart the tandem app
* in the tandem app, log out/in
* just wait

we've done the first two this morning, but the data hasn't started to flow yet
